# Generated by Django 5.2.8 on 2025-12-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Fútbol, Tenis', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('EQUIPO', 'Por Equipo'), ('INDIVIDUAL', 'Individual')], default='EQUIPO', max_length=20, verbose_name='Tipo de Deporte')),
                ('sistema_puntuacion', models.CharField(choices=[('GOLES', 'Goles (Fútbol, Balonmano)'), ('CANASTAS', 'Canastas/Puntos (Baloncesto)'), ('SETS', 'Sets (Tenis, Voleibol,Padel)'), ('PUNTOS', 'Puntos Genéricos')], default='PUNTOS', max_length=20, verbose_name='Sistema de Puntuación')),
                ('jugadores_por_equipo', models.PositiveIntegerField(default=1, help_text='Número de jugadores en campo por equipo', validators=[django.core.validators.MinValueValidator(1, 'Debe haber al menos 1 jugador')])),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('entrenador', models.CharField(help_text='Nombre del entrenador principal', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='SportApp.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('ha_pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('puntos_acumulados', models.IntegerField(default=0, verbose_name='Puntos Clasificación')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.equipo')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField(blank=True, help_text='Número entre 1 y 99', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='SportApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('temporada', models.CharField(help_text='Ej: 2024/2025', max_length=50)),
                ('estado', models.CharField(choices=[('INSCRIPCION', 'Inscripción Abierta'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='INSCRIPCION', max_length=20)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SportApp.deporte')),
                ('equipos', models.ManyToManyField(related_name='torneos_inscritos', through='SportApp.Inscripcion', to='SportApp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('jornada', models.CharField(help_text='Ej: Jornada 1', max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('JUGADO', 'Jugado / Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='PENDIENTE', max_length=20)),
                ('fase', models.CharField(choices=[('REGULAR', 'Fase Regular'), ('SEMIFINAL', 'Semifinal'), ('FINAL', 'Final')], default='REGULAR', max_length=20)),
                ('marcador_local', models.PositiveIntegerField(default=0)),
                ('marcador_visitante', models.PositiveIntegerField(default=0)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='SportApp.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='SportApp.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='SportApp.torneo')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.torneo'),
        ),
        migrations.CreateModel(
            name='EstadisticaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(default=0, verbose_name='Goles/Puntos/Canastas/Asistencias')),
                ('observaciones', models.TextField(blank=True, help_text='Incidencias, MVP, etc.', null=True)),
                ('minutos_jugados', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('juega', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportApp.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='SportApp.partido')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Partido',
                'unique_together': {('partido', 'jugador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('torneo', 'equipo')},
        ),
    ]
